language: c
sudo: true
deploy:
  provider: pypi
  user: bgruening
  skip_cleanup: true
  password:
    secure: ajVs2SKS8KcUiaw3LmvnhoUblMSHe9uyikN1uUmvQ5mHEBJXkpYw7YbvaSjV+ZnICuphi+o0OPn76writ3DBkhTwhzv8AP/UiCpktNRmtGb0WqbbJ3W/CDY8yTrAnmldd5LoK+aK4k00xDWSIi95atW3bAtGtm48+7sG2+VnvzY1DhVJJpcGUvPiA6xM8HHmpici2i19GimrhpB4A33kMZFDAECd9L/bpqEHU5lKz8H7JCFm2XngHEwtjof7Etroh/oSIVZk3qyP2uYP+Mo0hwF3KJbPWqC6pWpBZTKwvYULJAe4ndTYQhJnZqpJVZhBKWLr2VVN5bVDDoC7KhUibAwdAEipVF0a+Jo8Dt99PyzGEB5dw7qHPmF9iqGwRMNIZrAz4j6QobdFJBr0VDcfYD03jOhlInrv+WNJvjHNk3bvS3/VSSeEIFI5U9x8c5yV35eOmuSbeRsam6HnYRRnPKD3dcgap2PkhXbtUucyaQmsBzsRuD6dbbUZKGTflq6Trwo4tNtxOQaadyLnvqtl5lBtfkeYSOcyAtr2p6kW7ivpVn8BPONvTxD+x29Nyw3GA9BP3VQfR23Bzbx9sbnA6khX4RivB5Op36qJqIxpEszqWpy2zrOAUyfsN0RjO3kY+TAcf5QPosHXKRYdIY23pa8Y2q1qrz0ua0FRkWNDOIU=
  on:
    tags: true
  distributions: sdist bdist_wheel
  python:
  - 3.6
  - 3.7
env:
- TRAVIS_PYTHON_VERSION=3.6
- TRAVIS_PYTHON_VERSION=3.7
os:
- linux
- osx
stages:
- lint
- test
before_install:
- export HIC_TEST_DATA_DIR="`pwd`/hicmatrix/test/test_data/"
- echo $HIC_TEST_DATA_DIR
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -o miniconda.sh ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  -o miniconda.sh ; fi
- bash miniconda.sh -b -p $HOME/miniconda
- PATH_WITHOUT_CONDA="$PATH"
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
install:
- conda install --yes -c conda-forge -c bioconda python=$TRAVIS_PYTHON_VERSION --file
  requirements.txt
- conda install --yes -c conda-forge -c bioconda pytest
- conda install --yes flake8
- python setup.py install
script:
- flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F401,F403,E402,F999,F405,E712
- py.test hicmatrix/test/ --capture=sys
